sudo: required
language: java
jdk:
  - oraclejdk8
install: true

services:
  - docker

script:
  - cd customer-api
  - mvn test -Deureka.client.enabled=false  -B
  - mvn sonar:sonar -Dsonar.organization=usamamali-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=1b72ff80bd1c06456740dd5f56656a84a540a10b
  - cd ../vehicle-api
  - mvn test -Deureka.client.enabled=false  -B
  - mvn sonar:sonar -Dsonar.organization=usamamali-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=1b72ff80bd1c06456740dd5f56656a84a540a10b
  - cd ../vehicle-status-management
  - mvn test -Deureka.client.enabled=false  -B
  - mvn sonar:sonar -Dsonar.organization=usamamali-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=1b72ff80bd1c06456740dd5f56656a84a540a10b
  - cd ../customer-vehicle-management-api
  - mvn test -Deureka.client.enabled=false  -B
  - mvn sonar:sonar -Dsonar.organization=usamamali-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=1b72ff80bd1c06456740dd5f56656a84a540a10b

after_success:
  - docker-compose build --no-cache

notifications:
  email: false
