sudo: required
language: java
jdk:
  - oraclejdk8
install: true

services:
  - docker

script:
  - cd customer-api
  - mvn test -Deureka.client.enabled=false  -B
  - mvn sonar:sonar -Dsonar.organization=usamamali-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=1b72ff80bd1c06456740dd5f56656a84a540a10b
  - cd ../vehicle-api
  - mvn test -Deureka.client.enabled=false  -B
  - mvn sonar:sonar -Dsonar.organization=usamamali-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=1b72ff80bd1c06456740dd5f56656a84a540a10b
  - cd ../vehicle-status-management
  - mvn test -Deureka.client.enabled=false  -B
  - mvn sonar:sonar -Dsonar.organization=usamamali-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=1b72ff80bd1c06456740dd5f56656a84a540a10b
  - cd ../customer-vehicle-management-api
  - mvn test -Deureka.client.enabled=false  -B
  - mvn sonar:sonar -Dsonar.organization=usamamali-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=1b72ff80bd1c06456740dd5f56656a84a540a10b

after_success:
  # Stop containers and build our image
  - docker-compose build --no-cache
  # Push image to Docker Hub and update EB environment
  # - if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag vehicle_api $DOCKER_USERNAME/$vehicle_api:$TRAVIS_BUILD_ID;
    docker push $DOCKER_USERNAME/vehicle_api:$TRAVIS_BUILD_ID;
    #./scripts/upload_image_to_elastcbeanstalk.sh $TRAVIS_BUILD_ID $DEPLOYMENT_BUCKET $DEPLOYMENT_ENV $APP_NAME $DEPLOYMENT_REGION $IMAGE_NAME $DEPLOYMENT_ENV_NAME $DOCKER_USERNAME $DOCKER_REPOSITORY $DOCKER_PASSWORD $DOCKER_EMAIL;
   # fi

notifications:
  email: false
