version: '3.4'
services:
  discovery-service:
    build: ./vehicle-discovery-service
    image: usamamali/vehicle-discovery-service
    container_name: vehicle-discovery-service
    ports:
      - '8761:8761'

  vehicle-api:
    build: ./vehicle-api
    image: usamamali/vehicle-api
    container_name: vehicle-api
    ports:
      - '9091:9091'
    working_dir: /opt/app
    depends_on:
      - discovery-service

  customer-api:
    build: ./customer-api
    image: usamamali/customer-api
    container_name: customer-api
    ports:
      - '9092:9092'
    working_dir: /opt/app
    depends_on:
      - discovery-service

  customer-vehicle-management-api:
    build: ./customer-vehicle-management-api
    image: usamamali/customer-vehicle-management-api
    container_name: customer-vehicle-management-api
    ports:
      - '9093:9093'
    working_dir: /opt/app
    depends_on:
      - customer-api
      - vehicle-api
      - discovery-service

  vehicle-pulse-emulator:
    build: ./vehicle-pulse-emulator
    image: usamamali/vehicle-pulse-emulator
    container_name: vehicle-pulse-emulator
    ports:
      - '8060:8060'
    depends_on:
      - discovery-service
      - vehicle-api

  vehicle-status-management:
    build: ./vehicle-status-management
    image: usamamali/vehicle-status-management
    container_name: vehicle-status-management
    ports:
      - '8050:8050'
    depends_on:
      - discovery-service
      - customer-vehicle-management-api

  api-gateway:
    build: ./vehicle-monitor-api-gateway
    image: usamamali/vehicle-monitor-api-gateway
    container_name: vehicle-monitor-api-gateway
    ports:
      - '8080:8080'
    depends_on:
      - discovery-service
      - vehicle-api
      - customer-api
      - customer-vehicle-management-api
      - vehicle-status-management

  vehicle-monitor-ui:
    build: ./vehicle-monitoring-ui
    image: usamamali/vehicle-monitor-ui
    container_name: vehicle-monitor-ui
    ports:
      - '8888:80'
      - '4200:4200'
    depends_on:
      - api-gateway
